Passes relative path to rubocop
jsmecham/nova-rubocop pull request #11
Opened 2020-09-17 12:28 UTC by jbeker

Fixes: #10 

This tries to form a relative path based on the relationship to the root of the workspace directory. If it can do so, it uses that as the path that is given to the `--path` argument for `rubocop`. This allows inclusions and exclusions to work.

I'm not 100% happy with the path comparison, but it works. The paths that come from the file object seem to include the `/Volumes/Macintosh HD/Users` prefix while the workspace just starts with `/Users`. So I kind of just ignore that.

Open to suggestions.

2020-09-17 12:31 UTC, jsmecham requested changes
Nice work, you beat me to it! Does this resolve the behavior you're seeing?

2020-09-17 12:31 UTC, jsmecham commented on Source/Scripts/RuboCopProcess.js
> +
```suggestion

```

2020-09-17 12:31 UTC, jsmecham commented on Source/Scripts/RuboCopProcess.js
> +            relativePath = uri
```suggestion
            relativePath = uri;
```

2020-09-17 12:45 UTC, merged

2020-09-17 12:45 UTC, jsmecham commented
Thank you, @jbeker! Will cut a release this morning.

2020-09-17 12:51 UTC, jbeker commented
Yes it does. And thank you for having the extension to base it on. 

(And thanks for enduring the stream of consciousness bug report.)

2020-09-21 12:57 UTC, jsmecham commented
Finally got a chance to cut this release. You should be able to update to 0.5.1 now with this fix.